### ISSUE TITLE
geni-sync-wireless cron job fails

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/aws-transition#6]
The `geni-sync-wireless` cron job fails with the following error:

````
Date: Thu, 17 Nov 2016 02:00:02 +0000 (UTC)
From: "(Cron Daemon)" <root@>
To: root@
Subject: Cron <root@> /usr/bin/geni-sync-wireless --cleanup

Traceback (most recent call last):
  File "/usr/bin/geni-sync-wireless", line 782, in <module>
    sys.exit(main())
  File "/usr/bin/geni-sync-wireless", line 778, in main
    wpm.synchronize()
  File "/usr/bin/geni-sync-wireless", line 304, in synchronize
    self.get_geni_projects()
  File "/usr/bin/geni-sync-wireless", line 670, in get_geni_projects
    self._user)
  File "/usr/bin/geni-sync-wireless", line 650, in get_wimax_projects
    response = xmlrpc_client.lookup('PROJECT', credentials, options)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/lib64/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: 'CHAPIv1AuthorizationError: [AUTHORIZATION] AUTHORIZATION_ERROR (Client certificate required but not provided)'>
````

**Comment by tcmitchell** [comment]
The documentation for the `geni-sync-wireless` cron job seems to be out of date. It requires a certificate and key, something like this:

````
0 2 * * * /usr/local/bin/geni-sync-wireless -k /usr/share/geni-ch/portal/portal-key.pem -c /usr/share/geni-ch/portal/portal-cert.pem --cleanup
````

**Comment by tcmitchell** [comment]
We tested the fix of adding the `-c` and `-k` arguments to the cron job and that works. The documentation has also been updated to reflect this change.
